module.exports = {
  extends: ["prettier", "prettier/flowtype"],
  plugins: ["flowtype"],
  rules: {
    "flowtype/arrow-parens": "error",
    "flowtype/boolean-style": ["error", "boolean"],
    "flowtype/define-flow-type": "error",
    "flowtype/delimiter-dangle": "off",
    "flowtype/generic-spacing": ["error", "never"],
    "flowtype/no-dupe-keys": "error",
    "flowtype/no-primitive-constructor-types": "error",
    "flowtype/no-unused-expressions": "error",
    "flowtype/no-types-missing-file-annotation": "error",
    "flowtype/no-weak-types": "warn",
    "flowtype/object-type-delimiter": ["error", "comma"],
    "flowtype/require-indexer-name": "error",
    "flowtype/require-inexact-type": "error",
    "flowtype/require-readonly-react-props": "error",
    "flowtype/require-valid-file-annotation": "off",
    "flowtype/require-parameter-type": "off",
    "flowtype/require-return-type": "off",
    "flowtype/require-variable-type": "off",
    "flowtype/semi": "off",
    "flowtype/space-after-type-colon": ["error", "always"],
    "flowtype/space-before-generic-bracket": ["error", "never"],
    "flowtype/space-before-type-colon": ["error", "never"],
    "flowtype/type-id-match": "off",
    "flowtype/union-intersection-spacing": ["error", "always"],
    "flowtype/use-flow-type": "warn",
    "flowtype/array-style-complex-type": "error",
    "flowtype/array-style-simple-type": "error",
    "flowtype/require-compound-type-alias": "error",
    "flowtype/newline-after-flow-annotation": "error",
    "flowtype/no-existential-type": "error",
    "flowtype/no-flow-fix-me-comments": "warn",
    "flowtype/no-mixed": "off",
    "flowtype/no-mutable-array": "off",
    "flowtype/require-exact-type": ["error", "always"],
    "flowtype/require-types-at-top": "off",
    "flowtype/sort-keys": "off",
    "flowtype/type-import-style": "off",
    "flowtype/spread-exact-type": "off",
  },
};
