module.exports = {
  plugins: ["jest"],
  env: {
    "jest/globals": true,
  },
  rules: {
    "jest/consistent-test-it": "error",
    "jest/expect-expect": "off",
    "jest/lowercase-name": "off",
    "jest/no-alias-methods": "error",
    "jest/no-commented-out-tests": "error",
    "jest/no-disabled-tests": "warn",
    "jest/no-duplicate-hooks": "error",
    "jest/no-export": "error",
    "jest/no-focused-tests": "error",
    "jest/no-hooks": "off",
    "jest/no-if": "error",
    "jest/no-identical-title": "error",
    "jest/no-jasmine-globals": "error",
    "jest/no-jest-import": "error",
    "jest/no-large-snapshots": ["error", { maxSize: 32 }],
    "jest/no-mocks-import": "error",
    "jest/no-standalone-expect": "error",
    "jest/no-test-prefixes": "error",
    "jest/no-test-return-statement": "error",
    "jest/prefer-called-with": "error",
    "jest/prefer-expect-assertions": "off",
    "jest/prefer-inline-snapshots": "off",
    "jest/prefer-spy-on": "warn",
    "jest/prefer-strict-equal": "error",
    "jest/prefer-to-contain": "error",
    "jest/prefer-to-have-length": "error",
    "jest/prefer-todo": "warn",
    "jest/prefer-hooks-on-top": "error",
    "jest/require-top-level-describe": "off", // トップレベルにtestを書かせろ
    "jest/require-to-throw-message": "error",
    "jest/valid-describe": "off", // https://github.com/jest-community/eslint-plugin-jest/issues/203
    "jest/valid-expect": "error",
    "jest/valid-expect-in-promise": "error",
    "jest/valid-title": "error",
    "jest/no-conditional-expect": "error",
    "jest/no-deprecated-functions": "error",
    "jest/no-done-callback": "error",
    "jest/no-interpolation-in-snapshots": "error",
    "jest/no-restricted-matchers": "error",
    "jest/unbound-method": "off", // configure in `jest-and-typescript`
    "jest/max-nested-describe": "off",
    "jest/prefer-comparison-matcher": "error",
    "jest/prefer-equality-matcher": "error",
    "jest/prefer-expect-resolves": "error",
    "jest/prefer-lowercase-title": "off", // 日本語で書くので関心なし
    "jest/prefer-to-be": "error",
    "jest/require-hook": "error",
    "jest/valid-describe-callback": "error",
  },
};
