import { GLOB_SRC } from "../globs";
import { pluginJsdoc } from "../plugins";
import type { FlatConfigItem, OptionsOverride } from "../types";

export default function configsJsdoc(
  options: OptionsOverride,
): FlatConfigItem[] {
  return [
    {
      name: "berlysia:jsdoc",
      plugins: {
        jsdoc: pluginJsdoc,
      },
      rules: {
        "jsdoc/check-access": "warn",
        "jsdoc/check-alignment": "off",
        "jsdoc/check-examples": "off",
        "jsdoc/check-indentation": "off",
        "jsdoc/check-line-alignment": "off",
        "jsdoc/check-param-names": "warn",
        "jsdoc/check-property-names": "warn",
        "jsdoc/check-syntax": "warn",
        "jsdoc/check-tag-names": "warn",
        "jsdoc/check-types": "warn",
        "jsdoc/check-values": "warn",
        "jsdoc/empty-tags": "warn",
        "jsdoc/implements-on-classes": "warn",
        "jsdoc/imports-as-dependencies": "off",
        "jsdoc/match-name": "warn",
        "jsdoc/no-blank-blocks": "warn",
        "jsdoc/text-escaping": "warn",
        "jsdoc/informative-docs": "off",
        "jsdoc/match-description": "off",
        "jsdoc/multiline-blocks": "off",
        "jsdoc/no-bad-blocks": "off",
        "jsdoc/no-blank-block-descriptions": "off",
        "jsdoc/no-defaults": "off",
        "jsdoc/no-missing-syntax": "off",
        "jsdoc/no-multi-asterisks": "off",
        "jsdoc/no-restricted-syntax": "off",
        "jsdoc/no-types": "warn",
        "jsdoc/no-undefined-types": "off",
        "jsdoc/require-asterisk-prefix": "warn",
        "jsdoc/require-description": "off",
        "jsdoc/require-description-complete-sentence": "off",
        "jsdoc/require-example": "off",
        "jsdoc/require-file-overview": "off",
        "jsdoc/require-hyphen-before-param-description": "off",
        "jsdoc/require-jsdoc": "off",
        "jsdoc/require-param": "off",
        "jsdoc/require-param-description": "off",
        "jsdoc/require-param-name": "off",
        "jsdoc/require-param-type": "off",
        "jsdoc/require-property": "off",
        "jsdoc/require-property-description": "off",
        "jsdoc/require-property-name": "off",
        "jsdoc/require-property-type": "off",
        "jsdoc/require-returns": "off",
        "jsdoc/require-returns-check": "off",
        "jsdoc/require-returns-description": "off",
        "jsdoc/require-returns-type": "off",
        "jsdoc/require-throws": "off",
        "jsdoc/require-yields": "off",
        "jsdoc/require-yields-check": "off",
        "jsdoc/sort-tags": "off",
        "jsdoc/tag-lines": "off",
        "jsdoc/valid-types": "off",

        ...options.overrides,
      },
    },
  ];
}
