/**
 * Regenerates src/oxlint/supported-rules.ts from the installed oxlint's rule registry.
 *
 * The oxlint config generator drops rules that oxlint does not implement, because oxlint
 * rejects the whole config file when it contains an unknown rule. The registry is taken
 * from the pinned oxlint devDependency so that a Renovate bump of oxlint surfaces as a
 * diff (`--check` fails in CI until `pnpm run fix:oxlint-rules` is run).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type RegistryEntry = { scope: string; value: string; type_aware: boolean };

const outputPath = path.resolve(
  import.meta.dirname,
  "../src/oxlint/supported-rules.ts",
);

// oxlint reports some scopes with underscores while config files use hyphens
const normalizeScope = (scope: string) => scope.replaceAll("_", "-");

const registryJson = execFileSync("oxlint", ["--rules", "--format", "json"], {
  encoding: "utf8",
});
// eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion -- shape of `oxlint --rules --format json`
const registry = JSON.parse(registryJson) as RegistryEntry[];

const version = execFileSync("oxlint", ["--version"], { encoding: "utf8" })
  .replace("Version:", "")
  .trim();

const ruleIds = registry
  .map((entry) => `${normalizeScope(entry.scope)}/${entry.value}`)
  .sort();

const content = `// Generated by scripts/oxlint-rules.ts from oxlint ${version}. Do not edit by hand.
export const SUPPORTED_RULES: ReadonlySet<string> = new Set([
${ruleIds.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
]);
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== content) {
    console.error(
      "src/oxlint/supported-rules.ts is out of date with the installed oxlint. Run `pnpm run fix:oxlint-rules`.",
    );
    process.exitCode = 1;
  }
} else {
  writeFileSync(outputPath, content);
  console.log(`Wrote ${ruleIds.length} rules from oxlint ${version}`);
}
