module.exports = {
  parser: "babel-eslint",
  parserOptions: {
    ecmaVersion: 2017,
  },
  extends: ["eslint:recommended", "plugin:import/errors"],
  plugins: ["import", "import-order-autofix"],
  rules: {
    "consistent-return": "error",
    "class-methods-use-this": "error",
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    eqeqeq: "error",
    "no-console": "warn",
    "no-alert": "error",
    "no-caller": "error",
    "no-else-return": "error",
    "no-eq-null": "error",
    "no-extra-bind": "error",
    "no-implicit-coercion": "error",
    "no-param-reassign": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "error",
    "no-unmodified-loop-condition": "error",
    "no-unused-expressions": "error",
    "no-unused-vars": [
      "error",
      {
        args: "none",
        ignoreRestSiblings: true,
      },
    ],
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-return": "error",
    "no-warning-comments": "warn",
    radix: "error",
    "prefer-promise-reject-errors": [
      "error",
      {
        allowEmptyReject: true,
      },
    ],
    "no-shadow": "error",
    "no-bitwise": [
      "error",
      {
        int32Hint: true,
      },
    ],
    "no-negated-condition": "error",
    "no-plusplus": [
      "error",
      {
        allowForLoopAfterthoughts: true,
      },
    ],
    "operator-assignment": "error",
    "spaced-comment": "error",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "object-shorthand": "error",
    "no-var": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "import/newline-after-import": "error",
    "import/imports-first": "error",
    "import/prefer-default-export": "error",
    "import/no-dynamic-require": "error",
    "import/no-extraneous-dependencies": "error",
    "import/no-mutable-exports": "error",
    "import/no-commonjs": "error",
    "import-order-autofix/order": "error",
  },
};
