name: Renovate Auto Fix

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'package.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    # Renovate botのPRのみ実行
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 全履歴を取得してbase branchと比較できるように

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Detect package replacement
        id: detect
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: |
          REPLACEMENT=$(pnpm exec tsx scripts/renovate/detect-replacement.ts)
          if [ -n "$REPLACEMENT" ]; then
            echo "replacement=$REPLACEMENT" >> $GITHUB_OUTPUT
            echo "detected=true" >> $GITHUB_OUTPUT
          else
            echo "detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Apply replacement to src/plugins.ts
        if: steps.detect.outputs.detected == 'true'
        run: |
          pnpm exec tsx scripts/renovate/replace-package.ts ${{ steps.detect.outputs.replacement }}

      - name: Commit changes
        if: steps.detect.outputs.detected == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add src/plugins.ts
          git commit -m "chore: auto-update src/plugins.ts for package replacement

Automated update by GitHub Actions"
          git push
